[package]
name = "spaces-in-rust_log"
version = "0.1.0"
edition = "2021"

[features]
env_logger = []

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
tracing-subscriber = { version = "0.3.16", features = ['env-filter'] }
